name: running simple cypress test

on: 
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  cypress:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out
        uses: actions/checkout@v4 

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          spec: cypress/e2e/simple-test.cy.js
          browser: chrome
